// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 0_SmartPillBox

#include "../ui.h"

void ui_MainScr_screen_init(void)
{
    ui_MainScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_MainScr);
    lv_obj_set_width(ui_Panel2, 250);
    lv_obj_set_height(ui_Panel2, 180);
    lv_obj_set_x(ui_Panel2, 38);
    lv_obj_set_y(ui_Panel2, 20);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Date, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Date, "2023/02/02");
    lv_obj_set_style_text_font(ui_Date, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 0);
    lv_obj_set_y(ui_Time, 50);
    lv_obj_set_align(ui_Time, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Time, "09:05:00");
    lv_obj_set_style_text_font(ui_Time, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

	ui_Week = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Week, 0);
    lv_obj_set_y(ui_Week, 100);
    lv_label_set_text(ui_Week, "星期一");
    lv_obj_set_style_text_font(ui_Week, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_MainScr);
    lv_obj_set_width(ui_Panel3, 300);
    lv_obj_set_height(ui_Panel3, 187);
    lv_obj_set_x(ui_Panel3, -469);
    lv_obj_set_y(ui_Panel3, 218);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabBoxState = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabBoxState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabBoxState, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabBoxState, "药盒状态:");
    lv_obj_set_style_text_font(ui_LabBoxState, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BoxState = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_BoxState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BoxState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BoxState, 150);
    lv_obj_set_y(ui_BoxState, 0);
    lv_label_set_text(ui_BoxState, "关闭");
    lv_obj_set_style_text_font(ui_BoxState, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabTemperature = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabTemperature, 0);
    lv_obj_set_y(ui_LabTemperature, 50);
    lv_label_set_text(ui_LabTemperature, "药盒温度:");
    lv_obj_set_style_text_font(ui_LabTemperature, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 150);
    lv_obj_set_y(ui_Temperature, 50);
    lv_label_set_text(ui_Temperature, "26.8 ");
    lv_obj_set_style_text_font(ui_Temperature, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabHumidity = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabHumidity, 0);
    lv_obj_set_y(ui_LabHumidity, 100);
    lv_label_set_text(ui_LabHumidity, "药盒湿度:");
    lv_obj_set_style_text_font(ui_LabHumidity, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, 150);
    lv_obj_set_y(ui_Humidity, 100);
    lv_label_set_text(ui_Humidity, "53.1 ");
    lv_obj_set_style_text_font(ui_Humidity, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	ui_TempUnit = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_TempUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempUnit, 230);
    lv_obj_set_y(ui_TempUnit, 50);
    lv_label_set_text(ui_TempUnit, "℃");
    lv_obj_set_style_text_font(ui_TempUnit, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiUnit = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_HumiUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiUnit, 230);
    lv_obj_set_y(ui_HumiUnit, 100);
    lv_label_set_text(ui_HumiUnit, "%");
    lv_obj_set_style_text_font(ui_HumiUnit, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_MainScr);
    lv_obj_set_width(ui_Panel4, 300);
    lv_obj_set_height(ui_Panel4, 300);
    lv_obj_set_x(ui_Panel4, 464);
    lv_obj_set_y(ui_Panel4, -162);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabNextTime = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabNextTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabNextTime, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabNextTime, "下一次吃药时间:");
    lv_obj_set_style_text_font(ui_LabNextTime, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextTime = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_NextTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NextTime, 0);
    lv_obj_set_y(ui_NextTime, 40);
    lv_obj_set_align(ui_NextTime, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_NextTime, "无");
    lv_obj_set_style_text_color(ui_NextTime, lv_color_hex(0x2103F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NextTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NextTime, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabDrugName = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabDrugName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabDrugName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabDrugName, 0);
    lv_obj_set_y(ui_LabDrugName, 80);
    lv_label_set_text(ui_LabDrugName, "待服用药物名称:");
    lv_obj_set_style_text_font(ui_LabDrugName, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DrugName = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_DrugName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DrugName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DrugName, 0);
    lv_obj_set_y(ui_DrugName, 120);
    lv_obj_set_align(ui_DrugName, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_DrugName, "无");
    lv_obj_set_style_text_color(ui_DrugName, lv_color_hex(0x1F02F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DrugName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DrugName, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabDrugNumber = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabDrugNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabDrugNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabDrugNumber, 0);
    lv_obj_set_y(ui_LabDrugNumber, 160);
    lv_label_set_text(ui_LabDrugNumber, "需服用粒数:");
    lv_obj_set_style_text_font(ui_LabDrugNumber, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DrugNumber = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_DrugNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DrugNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DrugNumber, 0);
    lv_obj_set_y(ui_DrugNumber, 200);
    lv_obj_set_align(ui_DrugNumber, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_DrugNumber, "无");
    lv_obj_set_style_text_color(ui_DrugNumber, lv_color_hex(0x1F02F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DrugNumber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DrugNumber, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_MainScr);
    lv_obj_set_width(ui_Panel5, 150);
    lv_obj_set_height(ui_Panel5, 150);
    lv_obj_set_x(ui_Panel5, 133);
    lv_obj_set_y(ui_Panel5, 162);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgDrug = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_ImgDrug, &ui_img_drug_png);
    lv_obj_set_width(ui_ImgDrug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgDrug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgDrug, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImgDrug, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgDrug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabDrugManage = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_LabDrugManage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabDrugManage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabDrugManage, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabDrugManage, "药物管理");
    lv_obj_set_style_text_font(ui_LabDrugManage, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_MainScr);
    lv_obj_set_width(ui_Panel1, 150);
    lv_obj_set_height(ui_Panel1, 150);
    lv_obj_set_x(ui_Panel1, 290);
    lv_obj_set_y(ui_Panel1, 160);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgSetting = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_ImgSetting, &ui_img_setting_png);
    lv_obj_set_width(ui_ImgSetting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgSetting, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImgSetting, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label3, "系统设置");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	ui_Panel10 = lv_obj_create(ui_MainScr);
    lv_obj_set_width(ui_Panel10, 150);
    lv_obj_set_height(ui_Panel10, 150);
    lv_obj_set_x(ui_Panel10, -22);
    lv_obj_set_y(ui_Panel10, -142);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Panel10);
    lv_img_set_src(ui_Image2, &ui_img_close_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label16, "关闭药盒");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel5, ui_event_Panel5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
	lv_obj_add_event_cb(ui_Panel10, ui_event_Panel10, LV_EVENT_ALL, NULL);

	/********************** 自定义 *************************/
	lv_timer_create(update_time_cb, 1000, NULL);	//开启1s的定时器
}
