// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 0_SmartPillBox

#include "../ui.h"

void ui_SettingScr_screen_init(void)
{
    ui_SettingScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_SettingScr);
    lv_obj_set_width(ui_Panel12, 820);
    lv_obj_set_height(ui_Panel12, 60);
    lv_obj_set_x(ui_Panel12, -10);
    lv_obj_set_y(ui_Panel12, 0);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_Panel12);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_height(ui_ImgButton3, 64);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, -10);
    lv_obj_set_y(ui_ImgButton3, 5);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_LEFT_MID);

    ui_Label19 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "系统设置");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_SettingScr, LV_DIR_LEFT, 100);
    lv_obj_set_width(ui_TabView1, 800);
    lv_obj_set_height(ui_TabView1, 420);
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, 60);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView1), &ui_font_SourceHanSansCN30,
                               LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "关于");

    ui_Label18 = lv_label_create(ui_TabPage3);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18,
                      "          湖南工学院2024届\n物联网工程专业毕业设计作品\n\n          物联2001  罗泽旺");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_SourceHanSansCN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);

}
