// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 0_SmartPillBox

#include "ui.h"
#include "ui_helpers.h"
/* Hardware */
#include "ds3231.h"
/* C */
#include <stdio.h>
/* FreeRTOS */
#include "FreeRTOS.h"
#include "event_groups.h"
#include "lvgl_demo.h"

///////////////////// VARIABLES ////////////////////
/* 自定义 */
extern uint8_t flag_getTime;

DateTime dt;

// SCREEN: ui_StartScr
void ui_StartScr_screen_init(void);
lv_obj_t * ui_StartScr;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Spinner1;
void ui_event_BtnTest(lv_event_t * e);
lv_obj_t * ui_BtnTest;
lv_obj_t * ui_Label2;


// SCREEN: ui_MainScr
void ui_MainScr_screen_init(void);
lv_obj_t * ui_MainScr;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Date;
lv_obj_t * ui_Time;
lv_obj_t * ui_Week;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_LabBoxState;
lv_obj_t * ui_BoxState;
lv_obj_t * ui_LabTemperature;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_LabHumidity;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_TempUnit;
lv_obj_t * ui_HumiUnit;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_LabNextTime;
lv_obj_t * ui_NextTime;
lv_obj_t * ui_LabDrugName;
lv_obj_t * ui_DrugName;
lv_obj_t * ui_LabDrugNumber;
lv_obj_t * ui_DrugNumber;
void ui_event_Panel5(lv_event_t * e);
lv_obj_t * ui_Panel5;
lv_obj_t * ui_ImgDrug;
lv_obj_t * ui_LabDrugManage;
void ui_event_Panel1(lv_event_t * e);
lv_obj_t * ui_Panel1;
lv_obj_t * ui_ImgSetting;
lv_obj_t * ui_Label3;
void ui_event_Panel10(lv_event_t * e);
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label16;


// SCREEN: ui_DrugManageScr
void ui_DrugManageScr_screen_init(void);
lv_obj_t * ui_DrugManageScr;
lv_obj_t * ui_Panel6;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_DrugTable;


// SCREEN: ui_SettingScr
void ui_SettingScr_screen_init(void);
lv_obj_t * ui_SettingScr;
lv_obj_t * ui_Panel12;
void ui_event_ImgButton3(lv_event_t * e);
lv_obj_t * ui_ImgButton3;
lv_obj_t * ui_Label19;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_Label18;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BtnTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 100, &ui_MainScr_screen_init);
    }
}
void ui_event_Panel5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DrugManageScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 100, &ui_DrugManageScr_screen_init);
    }
}
void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 100, &ui_SettingScr_screen_init);
    }
}
void ui_event_Panel10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        //close_box_cb(e);
		//当点击关闭药盒图标，设置标志位
		xEventGroupSetBits(xEventGroup_SG90, SG90_OFF);
    }
}
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 100, &ui_MainScr_screen_init);
        _ui_screen_delete(&ui_DrugManageScr);
    }
}
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_SettingScr);
        _ui_screen_change(&ui_MainScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 100, &ui_MainScr_screen_init);
    }
}

/****************** 自定义，非squareline生成 **********************/
/* 每秒更新时间 */
void update_time_cb(lv_timer_t * timer)
{
    char time_str[9];
    char date_str[20];
    
    DS3231_GetTime(&dt);
    DS3231_GetDate(&dt);
	DS3231_GetWeek(&dt);

    snprintf(time_str, sizeof(time_str), "%02d:%02d:%02d", dt.hour_t, dt.minute_t, dt.second_t);
    snprintf(date_str, sizeof(date_str), "%04d/%02d/%02d", dt.year_t, dt.month_t, dt.day_t);

    lv_label_set_text(ui_Time, time_str);
    lv_label_set_text(ui_Date, date_str);
	
	switch(dt.week_t)
	{
		case 1:
			lv_label_set_text(ui_Week, "星期一");
			break;
		case 2:
			lv_label_set_text(ui_Week, "星期二");
			break;
		case 3:
			lv_label_set_text(ui_Week, "星期三");
			break;
		case 4:
			lv_label_set_text(ui_Week, "星期四");
			break;
		case 5:
			lv_label_set_text(ui_Week, "星期五");
			break;
		case 6:
			lv_label_set_text(ui_Week, "星期六");
			break;
		case 0:
			lv_label_set_text(ui_Week, "星期日");
			break;
		default:
			break;
	}
}

/******************************************************************/

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_StartScr_screen_init();
    ui_MainScr_screen_init();
    ui_DrugManageScr_screen_init();
    ui_SettingScr_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_StartScr);
}
