// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: 0_SmartPillBox

#ifndef _0_SMARTPILLBOX_UI_H
#define _0_SMARTPILLBOX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_StartScr
void ui_StartScr_screen_init(void);
extern lv_obj_t * ui_StartScr;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Spinner1;
void ui_event_BtnTest(lv_event_t * e);
extern lv_obj_t * ui_BtnTest;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_MainScr
void ui_MainScr_screen_init(void);
extern lv_obj_t * ui_MainScr;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Week;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_LabBoxState;
extern lv_obj_t * ui_BoxState;
extern lv_obj_t * ui_LabTemperature;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_LabHumidity;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_TempUnit;
extern lv_obj_t * ui_HumiUnit;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_LabNextTime;
extern lv_obj_t * ui_NextTime;
extern lv_obj_t * ui_LabDrugName;
extern lv_obj_t * ui_DrugName;
extern lv_obj_t * ui_LabDrugNumber;
extern lv_obj_t * ui_DrugNumber;
void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_ImgDrug;
extern lv_obj_t * ui_LabDrugManage;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_ImgSetting;
extern lv_obj_t * ui_Label3;
void ui_event_Panel10(lv_event_t * e);
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label16;
// SCREEN: ui_DrugManageScr
void ui_DrugManageScr_screen_init(void);
extern lv_obj_t * ui_DrugManageScr;
extern lv_obj_t * ui_Panel6;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_DrugTable;
// SCREEN: ui_SettingScr
void ui_SettingScr_screen_init(void);
extern lv_obj_t * ui_SettingScr;
extern lv_obj_t * ui_Panel12;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui____initial_actions0;

/******************* 自定义 ************************/
void update_time_cb(lv_timer_t * timer);

/***************************************************/

LV_IMG_DECLARE(ui_img_drug_png);    // assets\drug.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets\setting.png
LV_IMG_DECLARE(ui_img_close_png);    // assets\close.png
LV_IMG_DECLARE(ui_img_back_png);    // assets\back.png

LV_FONT_DECLARE(ui_font_SourceHanSansCN30);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
